apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-content-pvc
spec:
  accessModes:
    - ReadWriteMany           # ✅ Multiple pods/nodes can mount it
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-file-regional  # ✅ Use a File (RWX) storage class on IBM Cloud

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine   # ✅ Modern lightweight NGINX image
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 384Mi
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginx-content
      mountPath: /usr/share/nginx/html   # ✅ Content served from the persistent volume
  volumes:
  - name: nginx-content
    persistentVolumeClaim:
      claimName: nginx-content-pvc
